server:
  port: 8888
management:
  security:
    enabled: false
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
  profiles:
    active: jdbc

config:
  server:
    jdbc:
      driver.class.name: com.mysql.jdbc.Driver

cors.allowed.origins.regex: https?://(.*\.alphaea\.uk|localhost)(:\d{2,4})?
